common-steps: &common
  image: atlassianlabs/docker-node-jdk-chrome-firefox
  when:
    event: push

pipeline:

  install:
    <<: *common
    commands:
      - npm ci

  execute:
    image: selenium/standalone-chrome:85.0
    group: exe
    commands:
      - npm run test
