common-steps: &common
  image: atlassianlabs/docker-node-jdk-chrome-firefox
  when:
    event: push

pipeline:

  install:
    <<: *common
    commands:
      - npm ci

  execute:
    <<: *common
    commands:
      - npm run test

  execute-docker:
    image: docker
    commands:
      - npm run test
